In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df = pd.read_csv('Iris_dataset.csv')

In [6]:
df

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [7]:
df.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [35]:
info_data= {
    "Nom_et_prénom" : ["chaymae baya " , "zineb lahraoui " , "mehdi jamlaoui " , "mohammed majjadi" , "kaouthar chakor"] ,
    "CNE" : ["E13119762" , "E14119661" , "E15119764" , "C16120762" , "R14119762" ] ,
     "notes" : [15 , 17 , 12 , 20 , 16] ,
      "Mention": ["Bien", "Très Bien", "Passable", "Très Bien", "Bien"] ,
     "Filière": ["électronique ", "IA", "Mécanique ", "physique", "Télecommunication"] ,
     "Date_naissance": ["2000-02-22", "2000-02-28", "1999-10-07", "2001-12-01", "2001-06-22"] ,
    "Telephone": [ "0612345678", "0623456789",  "0634567890",  "0645678901", "0656789012"]
}

In [36]:
df = pd.DataFrame(info_data)

In [37]:
df

,Nom_et_prénom,CNE,notes,Mention,Filière,Date_naissance,Telephone
0,chaymae baya,E13119762,15,Bien,électronique,2000-02-22,0612345678
1,zineb lahraoui,E14119661,17,Très Bien,IA,2000-02-28,0623456789
2,mehdi jamlaoui,E15119764,12,Passable,Mécanique,1999-10-07,0634567890
3,mohammed majjadi,C16120762,20,Très Bien,physique,2001-12-01,0645678901
4,kaouthar chakor,R14119762,16,Bien,Télecommunication,2001-06-22,0656789012

In [23]:
df = df.set_index('Nom_et_prénom')

In [24]:
df

,CNE,notes,Mention,Filière,Date_naissance,Telephone
Nom_et_prénom,,,,,,
chaymae baya,E13119762,15,Bien,électronique,2000-02-22,0612345678
zineb lahraoui,E14119661,17,Très Bien,IA,2000-02-28,0623456789
mehdi jamlaoui,E15119764,12,Passable,Mécanique,1999-10-07,0634567890
mohammed majjadi,C16120762,20,Très Bien,physique,2001-12-01,0645678901
kaouthar chakor,R14119762,16,Bien,Télecommunication,2001-06-22,0656789012

In [25]:
df.sort_index()

,CNE,notes,Mention,Filière,Date_naissance,Telephone
Nom_et_prénom,,,,,,
chaymae baya,E13119762,15,Bien,électronique,2000-02-22,0612345678
kaouthar chakor,R14119762,16,Bien,Télecommunication,2001-06-22,0656789012
mehdi jamlaoui,E15119764,12,Passable,Mécanique,1999-10-07,0634567890
mohammed majjadi,C16120762,20,Très Bien,physique,2001-12-01,0645678901
zineb lahraoui,E14119661,17,Très Bien,IA,2000-02-28,0623456789

In [38]:
df.to_excel("info_data1.xlsx", index=False)

In [39]:
df.to_json("info_data2.json")

In [40]:
url = "https://jsonplaceholder.typicode.com/posts"

In [41]:
df = pd.read_json(url)

In [42]:
df

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

In [43]:
df.head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...